"""empty message

Revision ID: 6c211224f23d
Revises: 
Create Date: 2020-06-17 22:36:31.489882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c211224f23d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('shop_order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('shop_order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
